server:
  port: 8080  # Порт совпадает с docker-compose

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:6432/userdb  # Совпадает с docker-compose
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Берётся из env, но можно оставить для локальной работы
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG