server:
  port: 8083

spring:
  application:
    name: bid-service

  datasource:
    url: jdbc:postgresql://localhost:5434/bid_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    org.hibernate.SQL: DEBUG